logging:
  level:
    org.springframework.security: INFO
    org.springframework.batch: INFO
    com.neterium.client: INFO
    com.neterium.client.sdk.throttling: TRACE

server:
  port: 9003


# --- SpringBoot ---

spring:

  profiles:
    default: jetscan

  config:
    import: "file:.env[.properties]"

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  batch:
    job:
      # Disable auto-run on startup
      enabled: false

  datasource:
    hikari:
      maximum-pool-size: 100


# --- Neterium ---

neterium:

  http-client:
    connect-timeout: 30s
    read-timeout: 70s
    pool-size: 200

  oauth2:
    well-known-uri: https://connect-to.neterium.cloud/auth/realms/dev/.well-known/openid-configuration
    client-id: api

  api-keys:
    demo:
      username: "${SDK_USER}"
      password: "${SDK_PWD}"

  api-server:
    base-url: https://dev.neterium.cloud/api/v1
    key-id: demo

  throttling:
    window:
      size: 60s
    metric:
      name: MEAN
      min-count: 25
    durations:
      threshold-value: 1s
      threshold-ratio: 0.9
    timeouts:
      max-occurrences: 5
    calibration:
      initial-value: 3
      max-value: 20
      variation-amount: 0.025


# --- Demo app ---

demo:

  jobs:
    grid-size: 100
    min-partition-size: 250
    page-size: 500
